version: '3.8'
services:
  app:
    build:
      context: .
    volumes:
      - .:/natiq
    ports:
      - 3000:3000
    image: app:react
    container_name: react_container
    command: npm start

# run command: docker-compose up